package art.arcane.chimera.core.protocol;

import art.arcane.chimera.core.object.account.User;
import art.arcane.quill.collections.ID;

/**
 * This was generated by Chimera ProtoGen on Tue Mar 09 11:39:01 EST 2021
 */
public class EDN {

    public static class SERVICE {
        public static class Account {
            public static boolean accountEmailExists(String s) {
                return false;
            }

            public static User createUser(ID id, String s, String toLowerCase) {
                return null;
            }
        }

        public static class Gateway {
            public static void pushContext(ChimeraContext chimeraContext) {
            }
        }
    }

    public static class CLIENT {
        public static class Hawkeye {
            public static void snack2(String sessionId, String a, String b, boolean b1) {

            }

            public static void snack(String sessionId, String a, boolean b1) {

            }

            public static void snackConnectionError(String sessionId, String partial_service_outage, String s, boolean b) {
            }
        }
    }
}