/// Flutter icons Phoenicon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Phoenicon
///      fonts:
///       - asset: fonts/Phoenicon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Phoenicon {
  Phoenicon._();

  static const _kFontFam = 'Phoenicon';
  static const _kFontPkg = null;

  static const IconData phoenix =
      IconData(0xe877, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
