name: hawkeye_example
description: This isnt even used but idea and flutter like to complain if it doesnt exist...
version: 1.0.0
environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

