/// Flutter icons Krakicon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Krakicon
///      fonts:
///       - asset: fonts/Krakicon.ttf
///
///
///
import 'package:flutter/widgets.dart';

class Krakicon {
  Krakicon._();

  static const _kFontFam = 'Krakicon';
  static const _kFontPkg = null;

  static const IconData kraken =
      IconData(0xe879, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
