name: hawkeye
description: Hawkeye is a dart package indended to assist flutter apps use chimera
version: 1.0.0
environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  ## === NATIVE === ##
  charm: ^1.0.1
  crypto: ^3.0.0
  web_socket_channel: ^2.0.0
  path_provider: ^2.0.1
  url_launcher: ^5.7.10
  ## === DART === ##
  get: ^3.26.0
  fl_chart: ^0.20.1
  animator: ^2.0.2
  universal_html: ^1.2.4
  hive: ^2.0.0
  hive_flutter: ^1.0.0
  intl: ^0.17.0
  passwordfield: ^0.0.82
  auto_size_text: ^2.1.0
  liquid_swipe: ^1.5.0
  bloc: ^6.1.3
  flutter_bloc: ^6.1.3
  rxdart: ^0.26.0
assets:
  - assets/icon/